# Generated by Django 3.1 on 2020-08-21 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ratinge',
            new_name='rating',
        ),
    ]
